### ISSUE TITLE
Bug : impossible de créer une image avec une taille inférieure à 549 ko

### ISSUE THREAD

**Issue by Astuces-iOS** [istucesyt/DmgCreator#2]
Lorsque j'utilise dmgcreator et j'essaye de créer une image de moins de 549 ko. Une errer apparait. Il faut donc réouvrir l'App, remettre une nouvelle taille pour le dmg et remettre le titre. Comme ce bug ne pourrait peut-être pas être corrigé un avis pourrait aider les utilisateurs. À Propos un bouton annuler lors du message «Afin d'éviter toute erreur...» devrait être là pour revenir à l'accueil. L'utilisateur ne savais peut-être pas ça lorsqu'il aa rentré le nom du dmg. Il doit donc toucher ok pour avoir l'erreur et réouvrir l'App.

**Comment by istucesyt** [comment]
Merci d'avoir signalé ce désagrément.
Une image disque ne peut en effet posséder une taille inférieure à la taille que vous avez évoquée : le poids du conteneur et du titre de l'image en est la cause directe.
 
Pourriez-vous fournir un enregistrement de l'écran du plantage de l'application ?

**Comment by Astuces-iOS** [comment]
Le bug est désormais résolu lors de la dernière version de l'App.  
<img width="532" alt="Capture d’écran, le 2023-08-25 à 09 51 54" src="https://github.com/istucesyt/DmgCreator/assets/133143751/99eb2baa-e9c8-4a07-a16c-3cda06d0f0ea">

Malheureusement cette nouvelle version crée un bug qui affiche une alerte lorsqu'on crée un dmg correctement. Heureusement il est encore possible de créer des dmg : 
<img width="416" alt="Capture d’écran, le 2023-08-25 à 09 55 54" src="https://github.com/istucesyt/DmgCreator/assets/133143751/0590f178-dcbb-43ae-a89c-1537e3fad61f">
